import random
dice_roll = random.randint(1,6)
print(f'dice rolled: ', {dice_roll})
true = dice_roll == (1)
true = dice_roll == (6)
false = dice_roll == (2)
false = dice_roll == (3)
false = dice_roll == (4)
false = dice_roll == (5)
print(f'special number (1 or 6):', {true}) 